# Change these first
owner: 4rukadi # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository


sites:
     - name: HideSSH Website #web
       url: https://hidessh.com/
       icon: hhttps://hidessh.com/storage/site/hpc1FS8JlOINe59NamnPtIXgkWXxG1039sKp8uGG.png
       maxResponseTime: 5000
       expectedStatusCodes:
        - 200
        
     - name: HideSSH blog #blog
       url: https://hidessh.com/blog/
       icon: https://hidessh.com/storage/site/hpc1FS8JlOINe59NamnPtIXgkWXxG1039sKp8uGG.png
       maxResponseTime: 5000
       expectedStatusCodes:
        - 200
    

# service V2ray /Vmess HideSSH
    
     - name: SSH 🇮🇩 Indonesia #indo
       url: http://id.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500  
        
     - name: SSH 🇮🇩 Indonesia 2 #indo
       url: http://id2.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500
        
     - name: SSH 🇮🇩 Indonesia 3 #indo
       url: http://idku.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500  
        
     - name: SSH 🇮🇩 Indonesia 4 #indo
       url: http://id4.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500 
        
     - name: SSH 🇸🇬4 Singapura 4
       url: http://sg4.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500  
        
     - name: SSH 🇸🇬5 Singapura 5
       url: http://sg5.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500
        
     - name: SSH 🇸🇬 Singapura 
       url: http://sg.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500
        
     - name: SSH 🇸🇬2 Singapura 2
       url: http://sg2.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500
        
     - name: SSH 🇸🇬3 Singapura 3
       url: http://sg3.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500
        
     - name: SSH japan 
       url: http://jp.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500  
        
     - name: SSH Korea
       url: http://kr.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500  

     - name: SSH India
       url: http://in.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500  
        
     - name: SSH Australia
       url: http://au.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500        

     - name: SSH Canada
       url: http://ca.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500  
        
     - name: SSH US
       url: http://us.hideserver.xyz:8080/
       icon: https://hidessh.com/img/ssh.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500          
        
     - name: OpenVPN Singapura 5
       url: http://sg5.hideserver.xyz:8080/
       icon: https://hidessh.com/img/openvpn.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500

     - name: OpenVPN Japan 
       url: http://jp.hideserver.xyz:8080/
       icon: https://hidessh.com/img/openvpn.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500  
        
     - name: OpenVPN Korea
       url: http://kr.hideserver.xyz:8080/
       icon: https://hidessh.com/img/openvpn.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500  
    
     - name: OpenVPN India 
       url: http://in.hideserver.xyz:8080/
       icon: https://hidessh.com/img/openvpn.svg
       maxResponseTime: 5000
       expectedStatusCodes:
        - 400
        - 500  
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.hidessh.com
  # baseUrl: /your-repo-name
  favicon: https://hidessh.com/storage/site/hpc1FS8JlOINe59NamnPtIXgkWXxG1039sKp8uGG.png
  logoUrl: hhttps://hidessh.com/storage/site/hpc1FS8JlOINe59NamnPtIXgkWXxG1039sKp8uGG.png
  name: HideSSH.com - Server Status
  introTitle: "Welcome to our **HideSSH** server status page. "
  introMessage: You can get updates on how our systems are doing. If there are interruptions to service, we will post a note here.
  navbar:
    - title: HideSSH
      href: https://hidessh.com
    - title: Blog
      href: https://hidessh.com/blog
    - title: Telegram
      href: https://t.me/hidessh.com
  theme: light
  
# Upptime also supports notifications, assigning issues, and more
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
user-agent: 4rukadi

# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
